# -*- coding: utf-8 -*-
"""YeastGenes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1klU__m1pfNXwVuwW2TZO2KHpV0G7-BFZ
"""

import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn import cluster
from matplotlib import pyplot

import csv

from google.colab import drive
drive.mount('/content/drive')

def yeast_data():
	with open('/content/drive/My Drive/yeast_384_raw.txt') as f:
		reader = csv.reader(f, delimiter="\t")
		d = list(reader)
	# Now, clean your data by
	d2 = d[1:]
	data_matrix = []
	for row in d2:
		data_matrix.append(row[2:19])
	#data_matrix = d[1:-1][2:19]
	print (len(data_matrix))
	print (len(data_matrix[8]))

	print (data_matrix)
	return np.array(data_matrix)
dataset= yeast_data()
sklearn_pca = PCA(2)
data = dataset
sklearn_pca.fit_transform(dataset)
data = scale(dataset)



kmeans = KMeans(n_clusters= 5) 
y=kmeans.fit(data)
print(y.predict(data))

cluster_labels=kmeans.labels_
centroids = kmeans.cluster_centers_
c=5
for i in range(c):
    # observations with labels
    ds = data[np.where(cluster_labels==i)]
    # plot the data observations
    pyplot.plot(ds[:,0],ds[:,1],'o')
    # plot the centroids
    lines = pyplot.plot(centroids[i,0],centroids[i,1],'cx')
    # make the centroid x's visible
    pyplot.setp(lines,ms=15.0)
    pyplot.setp(lines,mew=2.0)
pyplot.show()